### ISSUE TITLE
Disable idle-kline prevention for authenticated users

### ISSUE THREAD

**Issue by madduck** [oftc/oftc-hybrid#46]
There are various reasons why one would want to reset the idle timer, and `PRIVMSG self` is the  usual way to do this. However, https://github.com/oftc/oftc-hybrid/blob/develop/modules/core/m_message.c#L607 explicitly prevents this, apparently to guard against "idle-kline circumvention".

Maybe this prevention could be put in place only against unauthenticated users, such that those authenticated with Services can reset their idle timers as they desire?

Thanks to @setharnold for hand-holding and finding the code.

**Comment by setharnold** [comment]
A message to self feels a lot kinder than e.g. messages to services; at least this wouldn't need to traverse multiple servers just for this feature.

Thanks
