### ISSUE TITLE
Letting users join/message regardless of registration (+R) requirement? 

### ISSUE THREAD

**Issue by Mikaela** [oftc/oftc-hybrid#63]
Channel ops with Matrix users on their channels at times ask how it's possible to reduce IRC spam while still allowing Matrix users to join easily e.g. at https://github.com/matrix-org/matrix-appservice-irc/issues/716 .

Is this possible with OFTC-Hybrid or can it become possible?

The [solutions on matrix-appservice-irc wiki](https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#i-am-a-chanop-and-have-a-spam-problem-how-can-i-fix-it-without-affecting-matrix-users) currently mostly suggests Charybdis specific modes:

* a mode to require TLS connections, I don't see equivalent in `/quote help cmode`
* an extban for muting unidentified users and a ban exception for Matrix users, `/quote help extban` doesn't find help and I don't see indication in `/quote help cmode` that this is supported
* two quiet solutions, but I don't see quiets in the help (but I see them in `/msg ChanServ help`?)
* an external bot which I imagine could work, but it's the least popular solution from what I can see.

* * * * *

Typing this issue, I think I may have found a solution:

> -- cmode :     +M     - 'Speak only if registered'. Client may speak only when registered and
> -- cmode :              identified to NickServ.

Can +v override +M? Do OFTC-IRCservices allow giving autovoice to everyone connecting from a specific IP range or hosts with wildcards (or however you define Matrix users)? How?

**Comment by df7cb** [comment]
Hi, there's more information on https://www.oftc.net/ChannelModes/, does that help?

**Comment by Mikaela** [comment]
I don't see the solution there.

**Comment by dwfreed** [comment]
We now allow +I (and it used to be +e, but switched to +I to match solanum; both work for now, but only +I will work on solanum) to bypass +R.
