### ISSUE TITLE
WHO <nick> returns no reply

### ISSUE THREAD

**Issue by emersion** [oftc/oftc-hybrid#64]
`WHO <nick>` returns no reply unless `<nick>` is the current user. `WHOIS` and `WHO <channel>` work fine.

**Comment by cryogen** [comment]
This is by design. WHO will not show +i clients to non opers, even if you name them expicitly

**Comment by emersion** [comment]
This breaks my client.

**Comment by cryogen** [comment]
Then your client is doing strange things and you should probably look for a new one :)

**Comment by emersion** [comment]
What do you mean by "strange things"? It's issuing a WHO command to retrieve a user's realname/away status/etc when opening a query buffer. The server incorrectly returns an empty WHO reply, and the client assumes the user is offline.

**Comment by emersion** [comment]
For the record, OFTC is the only server doing this. This works fine on all other servers I've tested.

**Comment by cryogen** [comment]
For clarify, I am no longer affiliated with OFTC and they may well decide to change this behaviour (There is actually a bug in that it should show users that share a channel with you, which it currently isn't doing). I'm just providing context as the person who wrote this code 20 odd years ago :)

**Comment by emersion** [comment]
TBH, I don't even understand the motivation for this behaviour. If this info can be queried via WHOIS, why refuse to make it available via WHO?

**Comment by cryogen** [comment]
WHO is(or was) super resource intensive. A conscious decision was made to make it as efficient as possible. This means that it behaves slightly differently from WHOIS.

```
  if(source_p != target_p && IsInvisible(target_p) && !showall)
    return 0;
```

This early return ensures that a lot of checks are not done when they don't need to be. In your particular instance this makes it slightly over zealous when you have a non wildcard nick search. If someone looking at this issue wants to fix it, making this check only for wildcard searches would be how I would do it

**Comment by emersion** [comment]
Cool, thanks for the details!

**Comment by emersion** [comment]
Submitted a patch addressing this at https://github.com/oftc/oftc-hybrid/pull/66.

**Comment by cryogen** [comment]
Shame, I was going to dust off my C compiler and have a go at this :D

For what my opinion is worth these days, the PR looks good to me

**Comment by df7cb** [comment]
It's a pity we missed that chance!

/me waves from the OFTC staff hideout

**Comment by cryogen** [comment]
Next time :)
